name: miot_spec
description: Dart implementation of MIoT specification.
version: 0.2.1
homepage: https://github.com/ctrysbita/miot-spec-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  dio: ^4.0.0-beta4
  json_annotation: ^4.0.0
  logger: ^1.0.0-nullsafety.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^4.0.0
  lints: ^1.0.1
  test: ^1.16.0
