name: miot_spec
description: Dart implementation of MIoT specification.
version: 0.5.1
homepage: https://github.com/ctrysbita/miot_spec.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  dio: ^4.0.0
  json_annotation: ^4.5.0
  logger: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  lints: ^2.0.0
  test: ^1.16.0
